Modified First Pull Request
Illegal32/student-service pull request #3
Opened 2022-07-06 06:31 UTC by Illegal32

2022-07-06 07:05 UTC, Illegal32 commented on src/main/groovy/az/pashabank/service/impl/StudentServiceImpl.java
> +    public Iterable<StudentEntity> findAll() {
replace with List

2022-07-08 10:35 UTC, validakhundov requested changes
Please be careful about naming

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/controller/StudentController.java
> +        var result = studentService.save(studentRequestDto);
why do you need ResponseEntity?)

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/service/impl/StudentServiceImpl.java
> +        return email.concat(DOMAIN);
let's do this with just one line:

return String.valueOf(name.charAt(0)).concat(surname).concat(String.valueOf(id)).concat(DOMAIN);

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/service/impl/StudentServiceImpl.java
> +        studentMapper = StudentMapper.INSTANCE;
this.

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/model/dto/StudentRequestDto.java
> +public class StudentRequestDto {
why do you need StudentRequestDto?

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/model/dto/StudentDto.java
> +public class StudentDto {
what's the difference between StudentDto and StudentEntity?

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/model/entity/StudentEntity.java
> +@Table(name = "student_info")
it's better to set table name just 'student'. Same as entity

2022-07-08 10:35 UTC, validakhundov commented on src/main/groovy/az/pashabank/service/StudentService.java
> +    StudentRequestDto save(StudentRequestDto studentRequestDto);
why save method returns StudentRequestDto?

2022-08-09 05:17 UTC, merged